#include "obsidiantrail/analysis/playbook.hpp"
#include "obsidiantrail/core/text.hpp"
#include <map>
#include <sstream>

namespace obsidiantrail::analysis {

const std::vector<PlaybookRule>& built_in_playbook() {
    static const std::vector<PlaybookRule> rules = {
        {"OT-PB-000", "initial-access", "script", "subject", "secret", 1, "Review subject values containing secret in initial-access context and compare adjacent timeline events"},
        {"OT-PB-001", "execution", "obfuscation", "host", "encoded", 2, "Review host values containing encoded in execution context and compare adjacent timeline events"},
        {"OT-PB-002", "persistence", "remote-service", "object", "kerberos", 3, "Review object values containing kerberos in persistence context and compare adjacent timeline events"},
        {"OT-PB-003", "privilege-escalation", "destruction", "process", "public", 4, "Review process values containing public in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-004", "defense-evasion", "service", "action", "download", 5, "Review action values containing download in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-005", "credential-access", "dumping", "path", "browser", 1, "Review path values containing browser in credential-access context and compare adjacent timeline events"},
        {"OT-PB-006", "discovery", "archive", "sensor", "admin", 2, "Review sensor values containing admin in discovery context and compare adjacent timeline events"},
        {"OT-PB-007", "lateral-movement", "phishing", "command", "delete", 3, "Review command values containing delete in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-008", "collection", "token", "note", "registry", 4, "Review note values containing registry in collection context and compare adjacent timeline events"},
        {"OT-PB-009", "exfiltration", "enumeration", "source", "rundll32", 5, "Review source values containing rundll32 in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-010", "impact", "cloud-sync", "tag", "archive", 1, "Review tag values containing archive in impact context and compare adjacent timeline events"},
        {"OT-PB-011", "initial-access", "script", "subject", "scheduled", 2, "Review subject values containing scheduled in initial-access context and compare adjacent timeline events"},
        {"OT-PB-012", "execution", "obfuscation", "host", "powershell", 3, "Review host values containing powershell in execution context and compare adjacent timeline events"},
        {"OT-PB-013", "persistence", "remote-service", "object", "rdp", 4, "Review object values containing rdp in persistence context and compare adjacent timeline events"},
        {"OT-PB-014", "privilege-escalation", "destruction", "process", "service", 5, "Review process values containing service in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-015", "defense-evasion", "service", "action", "edr", 1, "Review action values containing edr in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-016", "credential-access", "dumping", "path", "ssh", 2, "Review path values containing ssh in credential-access context and compare adjacent timeline events"},
        {"OT-PB-017", "discovery", "archive", "sensor", "backup", 3, "Review sensor values containing backup in discovery context and compare adjacent timeline events"},
        {"OT-PB-018", "lateral-movement", "phishing", "command", "vpn", 4, "Review command values containing vpn in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-019", "collection", "token", "note", "token", 5, "Review note values containing token in collection context and compare adjacent timeline events"},
        {"OT-PB-020", "exfiltration", "enumeration", "source", "credential", 1, "Review source values containing credential in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-021", "impact", "cloud-sync", "tag", "saml", 2, "Review tag values containing saml in impact context and compare adjacent timeline events"},
        {"OT-PB-022", "initial-access", "script", "subject", "secret", 3, "Review subject values containing secret in initial-access context and compare adjacent timeline events"},
        {"OT-PB-023", "execution", "obfuscation", "host", "encoded", 4, "Review host values containing encoded in execution context and compare adjacent timeline events"},
        {"OT-PB-024", "persistence", "remote-service", "object", "kerberos", 5, "Review object values containing kerberos in persistence context and compare adjacent timeline events"},
        {"OT-PB-025", "privilege-escalation", "destruction", "process", "public", 1, "Review process values containing public in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-026", "defense-evasion", "service", "action", "download", 2, "Review action values containing download in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-027", "credential-access", "dumping", "path", "browser", 3, "Review path values containing browser in credential-access context and compare adjacent timeline events"},
        {"OT-PB-028", "discovery", "archive", "sensor", "admin", 4, "Review sensor values containing admin in discovery context and compare adjacent timeline events"},
        {"OT-PB-029", "lateral-movement", "phishing", "command", "delete", 5, "Review command values containing delete in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-030", "collection", "token", "note", "registry", 1, "Review note values containing registry in collection context and compare adjacent timeline events"},
        {"OT-PB-031", "exfiltration", "enumeration", "source", "rundll32", 2, "Review source values containing rundll32 in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-032", "impact", "cloud-sync", "tag", "archive", 3, "Review tag values containing archive in impact context and compare adjacent timeline events"},
        {"OT-PB-033", "initial-access", "script", "subject", "scheduled", 4, "Review subject values containing scheduled in initial-access context and compare adjacent timeline events"},
        {"OT-PB-034", "execution", "obfuscation", "host", "powershell", 5, "Review host values containing powershell in execution context and compare adjacent timeline events"},
        {"OT-PB-035", "persistence", "remote-service", "object", "rdp", 1, "Review object values containing rdp in persistence context and compare adjacent timeline events"},
        {"OT-PB-036", "privilege-escalation", "destruction", "process", "service", 2, "Review process values containing service in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-037", "defense-evasion", "service", "action", "edr", 3, "Review action values containing edr in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-038", "credential-access", "dumping", "path", "ssh", 4, "Review path values containing ssh in credential-access context and compare adjacent timeline events"},
        {"OT-PB-039", "discovery", "archive", "sensor", "backup", 5, "Review sensor values containing backup in discovery context and compare adjacent timeline events"},
        {"OT-PB-040", "lateral-movement", "phishing", "command", "vpn", 1, "Review command values containing vpn in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-041", "collection", "token", "note", "token", 2, "Review note values containing token in collection context and compare adjacent timeline events"},
        {"OT-PB-042", "exfiltration", "enumeration", "source", "credential", 3, "Review source values containing credential in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-043", "impact", "cloud-sync", "tag", "saml", 4, "Review tag values containing saml in impact context and compare adjacent timeline events"},
        {"OT-PB-044", "initial-access", "script", "subject", "secret", 5, "Review subject values containing secret in initial-access context and compare adjacent timeline events"},
        {"OT-PB-045", "execution", "obfuscation", "host", "encoded", 1, "Review host values containing encoded in execution context and compare adjacent timeline events"},
        {"OT-PB-046", "persistence", "remote-service", "object", "kerberos", 2, "Review object values containing kerberos in persistence context and compare adjacent timeline events"},
        {"OT-PB-047", "privilege-escalation", "destruction", "process", "public", 3, "Review process values containing public in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-048", "defense-evasion", "service", "action", "download", 4, "Review action values containing download in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-049", "credential-access", "dumping", "path", "browser", 5, "Review path values containing browser in credential-access context and compare adjacent timeline events"},
        {"OT-PB-050", "discovery", "archive", "sensor", "admin", 1, "Review sensor values containing admin in discovery context and compare adjacent timeline events"},
        {"OT-PB-051", "lateral-movement", "phishing", "command", "delete", 2, "Review command values containing delete in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-052", "collection", "token", "note", "registry", 3, "Review note values containing registry in collection context and compare adjacent timeline events"},
        {"OT-PB-053", "exfiltration", "enumeration", "source", "rundll32", 4, "Review source values containing rundll32 in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-054", "impact", "cloud-sync", "tag", "archive", 5, "Review tag values containing archive in impact context and compare adjacent timeline events"},
        {"OT-PB-055", "initial-access", "script", "subject", "scheduled", 1, "Review subject values containing scheduled in initial-access context and compare adjacent timeline events"},
        {"OT-PB-056", "execution", "obfuscation", "host", "powershell", 2, "Review host values containing powershell in execution context and compare adjacent timeline events"},
        {"OT-PB-057", "persistence", "remote-service", "object", "rdp", 3, "Review object values containing rdp in persistence context and compare adjacent timeline events"},
        {"OT-PB-058", "privilege-escalation", "destruction", "process", "service", 4, "Review process values containing service in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-059", "defense-evasion", "service", "action", "edr", 5, "Review action values containing edr in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-060", "credential-access", "dumping", "path", "ssh", 1, "Review path values containing ssh in credential-access context and compare adjacent timeline events"},
        {"OT-PB-061", "discovery", "archive", "sensor", "backup", 2, "Review sensor values containing backup in discovery context and compare adjacent timeline events"},
        {"OT-PB-062", "lateral-movement", "phishing", "command", "vpn", 3, "Review command values containing vpn in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-063", "collection", "token", "note", "token", 4, "Review note values containing token in collection context and compare adjacent timeline events"},
        {"OT-PB-064", "exfiltration", "enumeration", "source", "credential", 5, "Review source values containing credential in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-065", "impact", "cloud-sync", "tag", "saml", 1, "Review tag values containing saml in impact context and compare adjacent timeline events"},
        {"OT-PB-066", "initial-access", "script", "subject", "secret", 2, "Review subject values containing secret in initial-access context and compare adjacent timeline events"},
        {"OT-PB-067", "execution", "obfuscation", "host", "encoded", 3, "Review host values containing encoded in execution context and compare adjacent timeline events"},
        {"OT-PB-068", "persistence", "remote-service", "object", "kerberos", 4, "Review object values containing kerberos in persistence context and compare adjacent timeline events"},
        {"OT-PB-069", "privilege-escalation", "destruction", "process", "public", 5, "Review process values containing public in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-070", "defense-evasion", "service", "action", "download", 1, "Review action values containing download in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-071", "credential-access", "dumping", "path", "browser", 2, "Review path values containing browser in credential-access context and compare adjacent timeline events"},
        {"OT-PB-072", "discovery", "archive", "sensor", "admin", 3, "Review sensor values containing admin in discovery context and compare adjacent timeline events"},
        {"OT-PB-073", "lateral-movement", "phishing", "command", "delete", 4, "Review command values containing delete in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-074", "collection", "token", "note", "registry", 5, "Review note values containing registry in collection context and compare adjacent timeline events"},
        {"OT-PB-075", "exfiltration", "enumeration", "source", "rundll32", 1, "Review source values containing rundll32 in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-076", "impact", "cloud-sync", "tag", "archive", 2, "Review tag values containing archive in impact context and compare adjacent timeline events"},
        {"OT-PB-077", "initial-access", "script", "subject", "scheduled", 3, "Review subject values containing scheduled in initial-access context and compare adjacent timeline events"},
        {"OT-PB-078", "execution", "obfuscation", "host", "powershell", 4, "Review host values containing powershell in execution context and compare adjacent timeline events"},
        {"OT-PB-079", "persistence", "remote-service", "object", "rdp", 5, "Review object values containing rdp in persistence context and compare adjacent timeline events"},
        {"OT-PB-080", "privilege-escalation", "destruction", "process", "service", 1, "Review process values containing service in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-081", "defense-evasion", "service", "action", "edr", 2, "Review action values containing edr in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-082", "credential-access", "dumping", "path", "ssh", 3, "Review path values containing ssh in credential-access context and compare adjacent timeline events"},
        {"OT-PB-083", "discovery", "archive", "sensor", "backup", 4, "Review sensor values containing backup in discovery context and compare adjacent timeline events"},
        {"OT-PB-084", "lateral-movement", "phishing", "command", "vpn", 5, "Review command values containing vpn in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-085", "collection", "token", "note", "token", 1, "Review note values containing token in collection context and compare adjacent timeline events"},
        {"OT-PB-086", "exfiltration", "enumeration", "source", "credential", 2, "Review source values containing credential in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-087", "impact", "cloud-sync", "tag", "saml", 3, "Review tag values containing saml in impact context and compare adjacent timeline events"},
        {"OT-PB-088", "initial-access", "script", "subject", "secret", 4, "Review subject values containing secret in initial-access context and compare adjacent timeline events"},
        {"OT-PB-089", "execution", "obfuscation", "host", "encoded", 5, "Review host values containing encoded in execution context and compare adjacent timeline events"},
        {"OT-PB-090", "persistence", "remote-service", "object", "kerberos", 1, "Review object values containing kerberos in persistence context and compare adjacent timeline events"},
        {"OT-PB-091", "privilege-escalation", "destruction", "process", "public", 2, "Review process values containing public in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-092", "defense-evasion", "service", "action", "download", 3, "Review action values containing download in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-093", "credential-access", "dumping", "path", "browser", 4, "Review path values containing browser in credential-access context and compare adjacent timeline events"},
        {"OT-PB-094", "discovery", "archive", "sensor", "admin", 5, "Review sensor values containing admin in discovery context and compare adjacent timeline events"},
        {"OT-PB-095", "lateral-movement", "phishing", "command", "delete", 1, "Review command values containing delete in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-096", "collection", "token", "note", "registry", 2, "Review note values containing registry in collection context and compare adjacent timeline events"},
        {"OT-PB-097", "exfiltration", "enumeration", "source", "rundll32", 3, "Review source values containing rundll32 in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-098", "impact", "cloud-sync", "tag", "archive", 4, "Review tag values containing archive in impact context and compare adjacent timeline events"},
        {"OT-PB-099", "initial-access", "script", "subject", "scheduled", 5, "Review subject values containing scheduled in initial-access context and compare adjacent timeline events"},
        {"OT-PB-100", "execution", "obfuscation", "host", "powershell", 1, "Review host values containing powershell in execution context and compare adjacent timeline events"},
        {"OT-PB-101", "persistence", "remote-service", "object", "rdp", 2, "Review object values containing rdp in persistence context and compare adjacent timeline events"},
        {"OT-PB-102", "privilege-escalation", "destruction", "process", "service", 3, "Review process values containing service in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-103", "defense-evasion", "service", "action", "edr", 4, "Review action values containing edr in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-104", "credential-access", "dumping", "path", "ssh", 5, "Review path values containing ssh in credential-access context and compare adjacent timeline events"},
        {"OT-PB-105", "discovery", "archive", "sensor", "backup", 1, "Review sensor values containing backup in discovery context and compare adjacent timeline events"},
        {"OT-PB-106", "lateral-movement", "phishing", "command", "vpn", 2, "Review command values containing vpn in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-107", "collection", "token", "note", "token", 3, "Review note values containing token in collection context and compare adjacent timeline events"},
        {"OT-PB-108", "exfiltration", "enumeration", "source", "credential", 4, "Review source values containing credential in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-109", "impact", "cloud-sync", "tag", "saml", 5, "Review tag values containing saml in impact context and compare adjacent timeline events"},
        {"OT-PB-110", "initial-access", "script", "subject", "secret", 1, "Review subject values containing secret in initial-access context and compare adjacent timeline events"},
        {"OT-PB-111", "execution", "obfuscation", "host", "encoded", 2, "Review host values containing encoded in execution context and compare adjacent timeline events"},
        {"OT-PB-112", "persistence", "remote-service", "object", "kerberos", 3, "Review object values containing kerberos in persistence context and compare adjacent timeline events"},
        {"OT-PB-113", "privilege-escalation", "destruction", "process", "public", 4, "Review process values containing public in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-114", "defense-evasion", "service", "action", "download", 5, "Review action values containing download in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-115", "credential-access", "dumping", "path", "browser", 1, "Review path values containing browser in credential-access context and compare adjacent timeline events"},
        {"OT-PB-116", "discovery", "archive", "sensor", "admin", 2, "Review sensor values containing admin in discovery context and compare adjacent timeline events"},
        {"OT-PB-117", "lateral-movement", "phishing", "command", "delete", 3, "Review command values containing delete in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-118", "collection", "token", "note", "registry", 4, "Review note values containing registry in collection context and compare adjacent timeline events"},
        {"OT-PB-119", "exfiltration", "enumeration", "source", "rundll32", 5, "Review source values containing rundll32 in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-120", "impact", "cloud-sync", "tag", "archive", 1, "Review tag values containing archive in impact context and compare adjacent timeline events"},
        {"OT-PB-121", "initial-access", "script", "subject", "scheduled", 2, "Review subject values containing scheduled in initial-access context and compare adjacent timeline events"},
        {"OT-PB-122", "execution", "obfuscation", "host", "powershell", 3, "Review host values containing powershell in execution context and compare adjacent timeline events"},
        {"OT-PB-123", "persistence", "remote-service", "object", "rdp", 4, "Review object values containing rdp in persistence context and compare adjacent timeline events"},
        {"OT-PB-124", "privilege-escalation", "destruction", "process", "service", 5, "Review process values containing service in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-125", "defense-evasion", "service", "action", "edr", 1, "Review action values containing edr in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-126", "credential-access", "dumping", "path", "ssh", 2, "Review path values containing ssh in credential-access context and compare adjacent timeline events"},
        {"OT-PB-127", "discovery", "archive", "sensor", "backup", 3, "Review sensor values containing backup in discovery context and compare adjacent timeline events"},
        {"OT-PB-128", "lateral-movement", "phishing", "command", "vpn", 4, "Review command values containing vpn in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-129", "collection", "token", "note", "token", 5, "Review note values containing token in collection context and compare adjacent timeline events"},
        {"OT-PB-130", "exfiltration", "enumeration", "source", "credential", 1, "Review source values containing credential in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-131", "impact", "cloud-sync", "tag", "saml", 2, "Review tag values containing saml in impact context and compare adjacent timeline events"},
        {"OT-PB-132", "initial-access", "script", "subject", "secret", 3, "Review subject values containing secret in initial-access context and compare adjacent timeline events"},
        {"OT-PB-133", "execution", "obfuscation", "host", "encoded", 4, "Review host values containing encoded in execution context and compare adjacent timeline events"},
        {"OT-PB-134", "persistence", "remote-service", "object", "kerberos", 5, "Review object values containing kerberos in persistence context and compare adjacent timeline events"},
        {"OT-PB-135", "privilege-escalation", "destruction", "process", "public", 1, "Review process values containing public in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-136", "defense-evasion", "service", "action", "download", 2, "Review action values containing download in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-137", "credential-access", "dumping", "path", "browser", 3, "Review path values containing browser in credential-access context and compare adjacent timeline events"},
        {"OT-PB-138", "discovery", "archive", "sensor", "admin", 4, "Review sensor values containing admin in discovery context and compare adjacent timeline events"},
        {"OT-PB-139", "lateral-movement", "phishing", "command", "delete", 5, "Review command values containing delete in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-140", "collection", "token", "note", "registry", 1, "Review note values containing registry in collection context and compare adjacent timeline events"},
        {"OT-PB-141", "exfiltration", "enumeration", "source", "rundll32", 2, "Review source values containing rundll32 in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-142", "impact", "cloud-sync", "tag", "archive", 3, "Review tag values containing archive in impact context and compare adjacent timeline events"},
        {"OT-PB-143", "initial-access", "script", "subject", "scheduled", 4, "Review subject values containing scheduled in initial-access context and compare adjacent timeline events"},
        {"OT-PB-144", "execution", "obfuscation", "host", "powershell", 5, "Review host values containing powershell in execution context and compare adjacent timeline events"},
        {"OT-PB-145", "persistence", "remote-service", "object", "rdp", 1, "Review object values containing rdp in persistence context and compare adjacent timeline events"},
        {"OT-PB-146", "privilege-escalation", "destruction", "process", "service", 2, "Review process values containing service in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-147", "defense-evasion", "service", "action", "edr", 3, "Review action values containing edr in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-148", "credential-access", "dumping", "path", "ssh", 4, "Review path values containing ssh in credential-access context and compare adjacent timeline events"},
        {"OT-PB-149", "discovery", "archive", "sensor", "backup", 5, "Review sensor values containing backup in discovery context and compare adjacent timeline events"},
        {"OT-PB-150", "lateral-movement", "phishing", "command", "vpn", 1, "Review command values containing vpn in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-151", "collection", "token", "note", "token", 2, "Review note values containing token in collection context and compare adjacent timeline events"},
        {"OT-PB-152", "exfiltration", "enumeration", "source", "credential", 3, "Review source values containing credential in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-153", "impact", "cloud-sync", "tag", "saml", 4, "Review tag values containing saml in impact context and compare adjacent timeline events"},
        {"OT-PB-154", "initial-access", "script", "subject", "secret", 5, "Review subject values containing secret in initial-access context and compare adjacent timeline events"},
        {"OT-PB-155", "execution", "obfuscation", "host", "encoded", 1, "Review host values containing encoded in execution context and compare adjacent timeline events"},
        {"OT-PB-156", "persistence", "remote-service", "object", "kerberos", 2, "Review object values containing kerberos in persistence context and compare adjacent timeline events"},
        {"OT-PB-157", "privilege-escalation", "destruction", "process", "public", 3, "Review process values containing public in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-158", "defense-evasion", "service", "action", "download", 4, "Review action values containing download in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-159", "credential-access", "dumping", "path", "browser", 5, "Review path values containing browser in credential-access context and compare adjacent timeline events"},
        {"OT-PB-160", "discovery", "archive", "sensor", "admin", 1, "Review sensor values containing admin in discovery context and compare adjacent timeline events"},
        {"OT-PB-161", "lateral-movement", "phishing", "command", "delete", 2, "Review command values containing delete in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-162", "collection", "token", "note", "registry", 3, "Review note values containing registry in collection context and compare adjacent timeline events"},
        {"OT-PB-163", "exfiltration", "enumeration", "source", "rundll32", 4, "Review source values containing rundll32 in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-164", "impact", "cloud-sync", "tag", "archive", 5, "Review tag values containing archive in impact context and compare adjacent timeline events"},
        {"OT-PB-165", "initial-access", "script", "subject", "scheduled", 1, "Review subject values containing scheduled in initial-access context and compare adjacent timeline events"},
        {"OT-PB-166", "execution", "obfuscation", "host", "powershell", 2, "Review host values containing powershell in execution context and compare adjacent timeline events"},
        {"OT-PB-167", "persistence", "remote-service", "object", "rdp", 3, "Review object values containing rdp in persistence context and compare adjacent timeline events"},
        {"OT-PB-168", "privilege-escalation", "destruction", "process", "service", 4, "Review process values containing service in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-169", "defense-evasion", "service", "action", "edr", 5, "Review action values containing edr in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-170", "credential-access", "dumping", "path", "ssh", 1, "Review path values containing ssh in credential-access context and compare adjacent timeline events"},
        {"OT-PB-171", "discovery", "archive", "sensor", "backup", 2, "Review sensor values containing backup in discovery context and compare adjacent timeline events"},
        {"OT-PB-172", "lateral-movement", "phishing", "command", "vpn", 3, "Review command values containing vpn in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-173", "collection", "token", "note", "token", 4, "Review note values containing token in collection context and compare adjacent timeline events"},
        {"OT-PB-174", "exfiltration", "enumeration", "source", "credential", 5, "Review source values containing credential in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-175", "impact", "cloud-sync", "tag", "saml", 1, "Review tag values containing saml in impact context and compare adjacent timeline events"},
        {"OT-PB-176", "initial-access", "script", "subject", "secret", 2, "Review subject values containing secret in initial-access context and compare adjacent timeline events"},
        {"OT-PB-177", "execution", "obfuscation", "host", "encoded", 3, "Review host values containing encoded in execution context and compare adjacent timeline events"},
        {"OT-PB-178", "persistence", "remote-service", "object", "kerberos", 4, "Review object values containing kerberos in persistence context and compare adjacent timeline events"},
        {"OT-PB-179", "privilege-escalation", "destruction", "process", "public", 5, "Review process values containing public in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-180", "defense-evasion", "service", "action", "download", 1, "Review action values containing download in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-181", "credential-access", "dumping", "path", "browser", 2, "Review path values containing browser in credential-access context and compare adjacent timeline events"},
        {"OT-PB-182", "discovery", "archive", "sensor", "admin", 3, "Review sensor values containing admin in discovery context and compare adjacent timeline events"},
        {"OT-PB-183", "lateral-movement", "phishing", "command", "delete", 4, "Review command values containing delete in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-184", "collection", "token", "note", "registry", 5, "Review note values containing registry in collection context and compare adjacent timeline events"},
        {"OT-PB-185", "exfiltration", "enumeration", "source", "rundll32", 1, "Review source values containing rundll32 in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-186", "impact", "cloud-sync", "tag", "archive", 2, "Review tag values containing archive in impact context and compare adjacent timeline events"},
        {"OT-PB-187", "initial-access", "script", "subject", "scheduled", 3, "Review subject values containing scheduled in initial-access context and compare adjacent timeline events"},
        {"OT-PB-188", "execution", "obfuscation", "host", "powershell", 4, "Review host values containing powershell in execution context and compare adjacent timeline events"},
        {"OT-PB-189", "persistence", "remote-service", "object", "rdp", 5, "Review object values containing rdp in persistence context and compare adjacent timeline events"},
        {"OT-PB-190", "privilege-escalation", "destruction", "process", "service", 1, "Review process values containing service in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-191", "defense-evasion", "service", "action", "edr", 2, "Review action values containing edr in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-192", "credential-access", "dumping", "path", "ssh", 3, "Review path values containing ssh in credential-access context and compare adjacent timeline events"},
        {"OT-PB-193", "discovery", "archive", "sensor", "backup", 4, "Review sensor values containing backup in discovery context and compare adjacent timeline events"},
        {"OT-PB-194", "lateral-movement", "phishing", "command", "vpn", 5, "Review command values containing vpn in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-195", "collection", "token", "note", "token", 1, "Review note values containing token in collection context and compare adjacent timeline events"},
        {"OT-PB-196", "exfiltration", "enumeration", "source", "credential", 2, "Review source values containing credential in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-197", "impact", "cloud-sync", "tag", "saml", 3, "Review tag values containing saml in impact context and compare adjacent timeline events"},
        {"OT-PB-198", "initial-access", "script", "subject", "secret", 4, "Review subject values containing secret in initial-access context and compare adjacent timeline events"},
        {"OT-PB-199", "execution", "obfuscation", "host", "encoded", 5, "Review host values containing encoded in execution context and compare adjacent timeline events"},
        {"OT-PB-200", "persistence", "remote-service", "object", "kerberos", 1, "Review object values containing kerberos in persistence context and compare adjacent timeline events"},
        {"OT-PB-201", "privilege-escalation", "destruction", "process", "public", 2, "Review process values containing public in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-202", "defense-evasion", "service", "action", "download", 3, "Review action values containing download in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-203", "credential-access", "dumping", "path", "browser", 4, "Review path values containing browser in credential-access context and compare adjacent timeline events"},
        {"OT-PB-204", "discovery", "archive", "sensor", "admin", 5, "Review sensor values containing admin in discovery context and compare adjacent timeline events"},
        {"OT-PB-205", "lateral-movement", "phishing", "command", "delete", 1, "Review command values containing delete in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-206", "collection", "token", "note", "registry", 2, "Review note values containing registry in collection context and compare adjacent timeline events"},
        {"OT-PB-207", "exfiltration", "enumeration", "source", "rundll32", 3, "Review source values containing rundll32 in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-208", "impact", "cloud-sync", "tag", "archive", 4, "Review tag values containing archive in impact context and compare adjacent timeline events"},
        {"OT-PB-209", "initial-access", "script", "subject", "scheduled", 5, "Review subject values containing scheduled in initial-access context and compare adjacent timeline events"},
        {"OT-PB-210", "execution", "obfuscation", "host", "powershell", 1, "Review host values containing powershell in execution context and compare adjacent timeline events"},
        {"OT-PB-211", "persistence", "remote-service", "object", "rdp", 2, "Review object values containing rdp in persistence context and compare adjacent timeline events"},
        {"OT-PB-212", "privilege-escalation", "destruction", "process", "service", 3, "Review process values containing service in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-213", "defense-evasion", "service", "action", "edr", 4, "Review action values containing edr in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-214", "credential-access", "dumping", "path", "ssh", 5, "Review path values containing ssh in credential-access context and compare adjacent timeline events"},
        {"OT-PB-215", "discovery", "archive", "sensor", "backup", 1, "Review sensor values containing backup in discovery context and compare adjacent timeline events"},
        {"OT-PB-216", "lateral-movement", "phishing", "command", "vpn", 2, "Review command values containing vpn in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-217", "collection", "token", "note", "token", 3, "Review note values containing token in collection context and compare adjacent timeline events"},
        {"OT-PB-218", "exfiltration", "enumeration", "source", "credential", 4, "Review source values containing credential in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-219", "impact", "cloud-sync", "tag", "saml", 5, "Review tag values containing saml in impact context and compare adjacent timeline events"},
        {"OT-PB-220", "initial-access", "script", "subject", "secret", 1, "Review subject values containing secret in initial-access context and compare adjacent timeline events"},
        {"OT-PB-221", "execution", "obfuscation", "host", "encoded", 2, "Review host values containing encoded in execution context and compare adjacent timeline events"},
        {"OT-PB-222", "persistence", "remote-service", "object", "kerberos", 3, "Review object values containing kerberos in persistence context and compare adjacent timeline events"},
        {"OT-PB-223", "privilege-escalation", "destruction", "process", "public", 4, "Review process values containing public in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-224", "defense-evasion", "service", "action", "download", 5, "Review action values containing download in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-225", "credential-access", "dumping", "path", "browser", 1, "Review path values containing browser in credential-access context and compare adjacent timeline events"},
        {"OT-PB-226", "discovery", "archive", "sensor", "admin", 2, "Review sensor values containing admin in discovery context and compare adjacent timeline events"},
        {"OT-PB-227", "lateral-movement", "phishing", "command", "delete", 3, "Review command values containing delete in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-228", "collection", "token", "note", "registry", 4, "Review note values containing registry in collection context and compare adjacent timeline events"},
        {"OT-PB-229", "exfiltration", "enumeration", "source", "rundll32", 5, "Review source values containing rundll32 in exfiltration context and compare adjacent timeline events"},
        {"OT-PB-230", "impact", "cloud-sync", "tag", "archive", 1, "Review tag values containing archive in impact context and compare adjacent timeline events"},
        {"OT-PB-231", "initial-access", "script", "subject", "scheduled", 2, "Review subject values containing scheduled in initial-access context and compare adjacent timeline events"},
        {"OT-PB-232", "execution", "obfuscation", "host", "powershell", 3, "Review host values containing powershell in execution context and compare adjacent timeline events"},
        {"OT-PB-233", "persistence", "remote-service", "object", "rdp", 4, "Review object values containing rdp in persistence context and compare adjacent timeline events"},
        {"OT-PB-234", "privilege-escalation", "destruction", "process", "service", 5, "Review process values containing service in privilege-escalation context and compare adjacent timeline events"},
        {"OT-PB-235", "defense-evasion", "service", "action", "edr", 1, "Review action values containing edr in defense-evasion context and compare adjacent timeline events"},
        {"OT-PB-236", "credential-access", "dumping", "path", "ssh", 2, "Review path values containing ssh in credential-access context and compare adjacent timeline events"},
        {"OT-PB-237", "discovery", "archive", "sensor", "backup", 3, "Review sensor values containing backup in discovery context and compare adjacent timeline events"},
        {"OT-PB-238", "lateral-movement", "phishing", "command", "vpn", 4, "Review command values containing vpn in lateral-movement context and compare adjacent timeline events"},
        {"OT-PB-239", "collection", "token", "note", "token", 5, "Review note values containing token in collection context and compare adjacent timeline events"},
    };
    return rules;
}

std::vector<PlaybookRule> rules_for_tactic(const std::string& tactic) {
    std::vector<PlaybookRule> out;
    for (const auto& rule : built_in_playbook()) {
        if (core::lower(rule.tactic) == core::lower(tactic)) out.push_back(rule);
    }
    return out;
}

static std::string event_field(const timeline::TimelineEvent& event, const std::string& field) {
    const auto& r = event.record;
    if (field == "action") return r.action;
    if (field == "object" || field == "path") return r.object;
    if (field == "subject") return r.subject;
    if (field == "source" || field == "host" || field == "sensor") return r.source;
    if (field == "tag") return core::join(r.tags, ",");
    auto it = r.fields.find(core::normalize_key(field));
    return it == r.fields.end() ? r.raw : it->second;
}

std::vector<std::string> apply_playbook(const timeline::Timeline& timeline) {
    std::vector<std::string> findings;
    for (const auto& event : timeline.events) {
        for (const auto& rule : built_in_playbook()) {
            auto value = event_field(event, rule.field);
            if (core::contains_folded(value, rule.needle)) {
                findings.push_back(rule.id + " " + rule.tactic + " " + rule.guidance);
            }
        }
    }
    return findings;
}

std::string summarize_playbook() {
    std::map<std::string, std::size_t> by_tactic;
    for (const auto& rule : built_in_playbook()) by_tactic[rule.tactic]++;
    std::ostringstream out;
    out << "playbook_rules=" << built_in_playbook().size();
    for (const auto& kv : by_tactic) out << "\n" << kv.first << "=" << kv.second;
    return out.str();
}

} // namespace obsidiantrail::analysis
